
---------------------------------- db sql start --------------------------------- 


/*users table 생성*/


  CREATE TABLE "SP365"."USERS" 
   (	"U_ID" VARCHAR2(20 BYTE), 
	"U_PWD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"U_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"U_TEL" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"U_IS_MGR" CHAR(1 BYTE) DEFAULT 'n', 
	"U_GENDER" CHAR(1 BYTE) NOT NULL ENABLE, 
	"U_AGE" NUMBER NOT NULL ENABLE, 
	"U_EMAIL" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"U_ADDRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"U_START_DATE" DATE DEFAULT SYSDATE, 
	"U_TOTAL_PRICE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "USER_ID_PK" PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365" ;
  
  
  
create sequence uid_seq start WITH 1 increment by 1;
insert into users(u_id, u_pwd , u_name, u_tel,u_gender, u_age, u_email, u_address, u_total_price) 
  values(uid_seq.nextval,'hennie','최희은','01029051070', 'f',28,'hennie92@naver.com','서울시 광진구',2000000 );

insert into users(u_id, u_pwd , u_name, u_tel,u_gender, u_age, u_email, u_address, u_total_price) 
  values(uid_seq.nextval,'jenny1020','김제니','01029051070', 'f',23,'jenny11@naver.com','서울시 은평구',14000000 );

insert into users(u_id, u_pwd , u_name, u_tel,u_is_mgr,u_gender, u_age, u_email, u_address, u_total_price) 
  values(uid_seq.nextval,'cucusuzzy11','배수지','01029051070', 'y','f',25,'hennie92@naver.com','서울시 강남구',144000000 );

insert into users(u_id, u_pwd , u_name, u_tel,u_gender, u_age, u_email, u_address, u_total_price) 
  values(uid_seq.nextval,'souhyun','김수현','01023251070', 'm',30,'jenny11@naver.com','서울시 용산구',300000 );
  



/*product table은 data import로 사용*/
-- PRODUCT TABLE에서 PRIMARY KEY 설정 --

ALTER TABLE product
     ADD CONSTRAINT product_pk_p_id primary  key (p_id);

/*board table*/



  CREATE TABLE "SP365"."BOARD" 
   (	"B_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"B_TITLE" VARCHAR2(100 BYTE), 
	"B_WRITER" VARCHAR2(20 BYTE), 
	"B_CONTENT" VARCHAR2(800 BYTE), 
	"B_REGDATE" DATE DEFAULT SYSDATE, 
	"B_REPLY" VARCHAR2(20 BYTE), 
	"U_ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "BOARD_PK_B_ID" PRIMARY KEY ("B_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365"  ENABLE, 
	 CONSTRAINT "BOARD_FK_U_ID" FOREIGN KEY ("U_ID")
	  REFERENCES "SP365"."USERS" ("U_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365" ;



create sequence cid_seq start WITH 1 increment by 1;
 insert into cart(c_id, c_qty , c_size,c_regdate,o_id , p_id , u_id) 
   values(  concat('cart' ,TO_CHAR(cid_seq.nextval)),2, 'S',sysdate, 4347790481001,'top_11','1' );
   
 insert into cart(c_id, c_qty , c_size,c_regdate,o_id , p_id , u_id) 
   values(  concat('cart' ,TO_CHAR(cid_seq.nextval)),1, 'M',sysdate,1326804101008,'acc_13','2' );


 insert into cart(c_id, c_qty , c_size,c_regdate,o_id , p_id , u_id) 
   values(  concat('cart' ,TO_CHAR(cid_seq.nextval)),4, 'L',sysdate ,null,'outer_11','2' );
  
  



/*cart table 형성*/


 CREATE TABLE "SP365"."CART" 
   (	"C_ID" VARCHAR2(20 BYTE), 
	"C_QTY" NUMBER DEFAULT 0, 
	"C_SIZE" VARCHAR2(10 BYTE), 
	"C_SUM" NUMBER(38,0), 
	"C_REGDATE" DATE DEFAULT SYSDATE, 
	"O_ID" VARCHAR2(30 BYTE), 
	"P_ID" VARCHAR2(26 BYTE), 
	"U_ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_CART_C_ID" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365"  ENABLE, 
	 CONSTRAINT "FK_CART_P_ID" FOREIGN KEY ("P_ID")
	  REFERENCES "SP365"."PRODUCT" ("P_ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "FK_CART_U_ID" FOREIGN KEY ("U_ID")
	  REFERENCES "SP365"."USERS" ("U_ID") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365" ;
  
  
  
  
create sequence cid_seq start WITH 1 increment by 1;

 insert into cart(c_id, c_qty , c_size,c_regdate,o_id , p_id , u_id) 
   values(  concat('cart' ,TO_CHAR(cid_seq.nextval)),2, 'S',sysdate, 4347790481001,'top_11','1' );

 insert into cart(c_id, c_qty , c_size,c_regdate,o_id , p_id , u_id) 
   values(  concat('cart' ,TO_CHAR(cid_seq.nextval)),1, 'M',sysdate,1326804101008,'acc_13','2' );


 insert into cart(c_id, c_qty , c_size,c_regdate,o_id , p_id , u_id) 
   values(  concat('cart' ,TO_CHAR(cid_seq.nextval)),4, 'L',sysdate ,null,'outer_11','2' );
  
  /*orders table 형성*/
  
  
  CREATE TABLE "SP365"."ORDERS" 
   (	"O_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"O_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"O_TEL" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"O_EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"O_ADDRESS" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"O_REGDATE" DATE DEFAULT SYSDATE, 
	"O_TOTAL" NUMBER NOT NULL ENABLE, 
	"O_PAYMENT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"U_ID" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_ORDERS_O_ID" PRIMARY KEY ("O_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365"  ENABLE, 
	 CONSTRAINT "FK_ORDERS_U_ID" FOREIGN KEY ("U_ID")
	  REFERENCES "SP365"."USERS" ("U_ID") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SP365" ;



INSERT INTO ORDERS
  VALUES(CEIL(DBMS_RANDOM.value(1,10)*100000000)||seq_orders.NEXTVAL,'id01','010','a@gmail.com','멀티캠퍼스','99',SYSDATE,50000,'무통장입금','id01');
INSERT INTO ORDERS
  VALUES(CEIL(DBMS_RANDOM.value(1,10)*100000000)||seq_orders.NEXTVAL,'id02','010','b@gmail.com','서울시','99',ADD_MONTHS(SYSDATE, -1),120000,'신용카드','id02');
INSERT INTO ORDERS
  VALUES(CEIL(DBMS_RANDOM.value(1,10)*100000000)||seq_orders.NEXTVAL,'id04','010','c@gmail.com','경기도','99',ADD_MONTHS(SYSDATE, -2),30000,'무통장입금','id04');
INSERT INTO ORDERS
  VALUES(CEIL(DBMS_RANDOM.value(1,10)*100000000)||seq_orders.NEXTVAL,'aaaa','010','d@gmail.com','멀캠','99',ADD_MONTHS(SYSDATE, -3),70000,'무통장입금','aaaa');
INSERT INTO ORDERS
  VALUES(CEIL(DBMS_RANDOM.value(1,10)*100000000)||seq_orders.NEXTVAL,'ffff','010','e@gmail.com','역삼','99',ADD_MONTHS(SYSDATE, -4),60000,'신용카드','ffff');
  




  
---------------------------------- db sql end --------------------------------- 







